## Shortcuts tensorflow

In [3]:
# make imports
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

# Example of create arrays/ matrix

In [28]:
# use method "astype(np.float32)" is important, because *np.array* by default use int64 \
# Tensorflow calculate  preferly float16/32/64 and complex 
# astype downcast object

first_array = tf.constant(np.arange(0,100).reshape(10,10).astype(np.float32))

In [17]:
# Tensorflow Variable and Placeholder only "reserve" memory for array
# (actually add in graph, which is must be "launched")

second_array = tf.Variable(np.array(np.mat('1 2; 3 4')))

In [18]:
# So, if you want to print this array, you' ll see something like this: 
# <tf.Variable 'Variable:0' shape=(2, 2) dtype=int64_ref>
# By the way look at dtype, it's int64, which tensorflow don't "like" :)

second_array

<tf.Variable 'Variable_2:0' shape=(2, 2) dtype=int64_ref>

In [21]:
third_array = tf.Variable(np.array([[1,2,3], [4,5,6]]).astype(np.float32))
third_array

<tf.Variable 'Variable_5:0' shape=(2, 3) dtype=float32_ref>

In [34]:


# Lets see on our 2D arrays

init = tf.global_variables_initializer()

with tf.Session() as sess:
    
    sess.run(init)
    
    print("First matrix:\n{0}\n\nSecond matrix:\n{1}\n\nThird matrix:\n{2}".format(sess.run(first_array), 
                                                                            sess.run(second_array),
                                                                            sess.run(third_array)))

First matrix:
[[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.]
 [ 10.  11.  12.  13.  14.  15.  16.  17.  18.  19.]
 [ 20.  21.  22.  23.  24.  25.  26.  27.  28.  29.]
 [ 30.  31.  32.  33.  34.  35.  36.  37.  38.  39.]
 [ 40.  41.  42.  43.  44.  45.  46.  47.  48.  49.]
 [ 50.  51.  52.  53.  54.  55.  56.  57.  58.  59.]
 [ 60.  61.  62.  63.  64.  65.  66.  67.  68.  69.]
 [ 70.  71.  72.  73.  74.  75.  76.  77.  78.  79.]
 [ 80.  81.  82.  83.  84.  85.  86.  87.  88.  89.]
 [ 90.  91.  92.  93.  94.  95.  96.  97.  98.  99.]]

Second matrix:
[[1 2]
 [3 4]]

Third matrix:
[[ 1.  2.  3.]
 [ 4.  5.  6.]]


# Tensorflow way to create array/ matrix 

In [39]:
mat = tf.fill((4,4),10)
zeros = tf.zeros((4,4))
ones = tf.ones((4,4))
# Outputs random values from a normal distribution.
myrandn = tf.random_normal((4,4), mean=0,stddev=1.0)
# Outputs random values from a uniform distribution in range [minval, maxval) (maxval not included)
myrandu = tf.random_uniform((4,4), minval=0,maxval=1)
random_array = tf.random_uniform((4,4),0,1)

In [42]:
init = tf.global_variables_initializer()

with tf.Session() as sess:
    
    sess.run(init)
    
    print("Filled matrix:\n{0}\n\nZero matrix:\n{1}\n\nOne matrix:\n{2} \
          \n\nNormal distribution matrix:\n{3}\n\nUnifrom distribution matrix:\n{4}".format(sess.run(mat), 
                                                                                            sess.run(zeros),
                                                                                            sess.run(ones),
                                                                                            sess.run(myrandn),
                                                                                           sess.run(myrandu)))

Filled matrix:
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]

Zero matrix:
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]

One matrix:
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]           

Normal distribution matrix:
[[ 0.71059412  0.45923781  1.31372058  0.06984565]
 [ 1.39448786 -0.17147513  0.29217905  0.57181448]
 [ 0.58708775  0.42203256 -0.60047865  2.52088666]
 [-2.21023536  0.57852846 -0.39603317  0.73772901]]

Unifrom distribution matrix:
[[ 0.67458093  0.2460438   0.25704181  0.52135265]
 [ 0.95052707  0.39477873  0.17478287  0.63583553]
 [ 0.38984215  0.13867116  0.64462602  0.19409668]
 [ 0.02853441  0.72712016  0.05596697  0.04120505]]
